import math
import random
import yaml

CUBE_WIDTH = 3

def load_inchworm_motor_offsets_bounds(config_file):
    """
    Loads motor offsets for an inchworm robot from a YAML configuration file.
    
    Args:
        config_file (str): Path to the YAML configuration file containing motor offsets.
        
    Returns:
        dict: A dictionary containing motor offset values for theta1, theta2, theta3, theta4, and theta5.
    """
    # Open the YAML configuration file in read mode
    with open(config_file, 'r') as file:
        # Parse the YAML content and load it into a Python dictionary
        config = yaml.safe_load(file)
    
    # Return the motor offsets from the configuration dictionary
    return config['motor_offsets'], config['motor_bounds']

def apply_offsets(theta_values, motor_offsets):
    """
    Applies motor offsets to the calculated joint angles (theta values).
    
    Args:
        theta_values (list): A list of calculated joint angles [theta1, theta2, theta3, theta4, theta5].
        motor_offsets (dict): A dictionary containing motor offset values for each joint.
        
    Returns:
        list: A list of adjusted joint angles with the corresponding offsets applied.
    """
    return [
        theta_values[0] + motor_offsets['theta1'],
        theta_values[1] + motor_offsets['theta2'],
        theta_values[2] + motor_offsets['theta3'],
        theta_values[3] + motor_offsets['theta4'],
        theta_values[4] + motor_offsets['theta5']
    ]

def check_motor_bounds(theta_values, motor_bounds):
    """
    Compares the inputted motor values to the bounds to ensure that the robot does not try to move to 
    a position that is impossible (because the link gets in the way). Raises an error if motor values 
    are unsafe

    Args:
        theta_values (list): A list of calculated joint angles [theta1, theta2, theta3, theta4, theta5].
        motor_bounds (dict): A dictionary containing motor bounds for each joint.
    """
    if not (theta_values[1] > motor_bounds['joint2_outer_bound'] and theta_values[1] < motor_bounds['joint2_inner_bound'] and
            theta_values[2] > motor_bounds['joint3_outer_bound'] and theta_values[2] < motor_bounds['joint3_inner_bound'] and
            theta_values[3] < motor_bounds['joint4_outer_bound'] and theta_values[3] > motor_bounds['joint4_inner_bound']):
        ValueError("Motor values out of safe bounds")

def adjust_positions(goal_X: float, goal_Y: float, goal_Z: float, pivot_foot: int): 

        """
        Helper function to adjust the goal EE position to a format digestable for the inverse kinematics. These numbers were generated by collecting different 
        desired and actual positons. Refer to the drive for the sheet for the data

        Args:
            goal_X (float): the desired X position in number of blocks. 
            goal_Y (float): the desired Y position in number of blocks. 
            goal_Z (float): the desired Z position in number of blocks. 
            pivot_foot (int): Motor identifier (1 or 5) corresponding to the pivotal foot.
        Returns: 
            list: 3x1 list 
        """
        if (pivot_foot == 1):
            inputX = CUBE_WIDTH * 1.244 * goal_X + 0.1242
            inputY = CUBE_WIDTH * 1.2595 * goal_Y + 0.0249
            inputZ = CUBE_WIDTH * 1.0786 * goal_Z - 0.0432
        elif (pivot_foot == 5):
            inputX = CUBE_WIDTH * 1.0158 * goal_X - 0.0059
            inputY = CUBE_WIDTH * 1.0101 * goal_Y - 0.0204
            inputZ = (-0.0233 * (CUBE_WIDTH * goal_Z)**2) + (CUBE_WIDTH * 1.2747 * goal_Z) + 0.4137
        # if (pivot_foot == 1):
        #     inputX = CUBE_WIDTH * goal_X + 1.2
        #     inputY = CUBE_WIDTH * goal_Y
        #     inputZ = CUBE_WIDTH * goal_Z + 1.6
        # elif (pivot_foot == 5):
        #     inputX = CUBE_WIDTH * goal_X
        #     inputY = CUBE_WIDTH * goal_Y
        #     inputZ = CUBE_WIDTH * goal_Z
        
        return [inputX, inputY, inputZ]
        

def inverseKinematics(Px, Py, Pz, alpha, pivot_foot: int, fix_EE_orientation: bool):
    """
    Calculates inverse kinematics for inchworm robot and adjusts motor angles using offsets.
    
    Args:
        Px (float): X coordinate of the end-effector corresponding to pivot_foot.
        Py (float): Y coordinate of the end-effector corresponding to pivot_foot.
        Pz (float): Z coordinate of the end-effector corresponding to pivot_foot.
        alpha (float): The angle of the wrist joint (motor 2 or 4) w.r.t. the horizontal plane. 
            0 deg for horizontal, 90 deg for pointing down.
        pivot_foot (int): Motor identifier (1 or 5) corresponding to the foot.
        fix_EE_orientation (bool): True if the EE rotation is being reset to 0. 
    
    Returns:
        list: A list of joint angles [theta1, theta2, theta3, theta4, theta5] adjusted for motor offsets.
    """

    # These calculations are in inches 
    L_BASE = 3.16  # base to joint 1
    L1 = 1.15        # Joint 1 to Joint 2
    L2 = 6.43      # Joint 2 to Joint 3
    L3 = 6.67      # Joint 3 to Joint 4
    L4 = 1.17        # Joint 4 to Joint 5
    L_ENDEFFECTOR = 3.18  # Joint 5 to EE

    # extract the motor offsets from the yaml file
    inchworm_motor_offsets, inchworm_motor_bounds = load_inchworm_motor_offsets_bounds('/home/smac/robot_ws/src/SMAC6.0/inchworm_control/inchworm_control/inchworm_motor_config.yaml')
    [Px, Py, Pz] = adjust_positions(Px, Py, Pz, pivot_foot)    

    
    # Convert alpha angle from degrees to radians 
    alpha = math.radians(alpha)

    # error catching: Robot cannot reach the point
    maxDistArmZ = L_BASE + L1 + L2 + L3 + L4 + L_ENDEFFECTOR # max Distance the arm can reach in z axis
    maxDistArmXY = L2 + L3 + L4 + L_ENDEFFECTOR # max Distance the arm can reach in x or y axis

    # throws error if coordinate is too far for the robot to reach
    if(Px > maxDistArmXY or Py > maxDistArmXY or Pz > maxDistArmZ): 
        ValueError("NOOOO MY LEGS ARE TOO SHORT :(")

    # See inverse kinematics derivation in the SMAC 6.0 Google Drive folder 
    # Calculate the pose in the XZ-plane 
    r = math.sqrt(Px**2 + Py**2) # distance along the ground (z=0) from robot origin to EE positiion 
    r_4 = r - (L4+L_ENDEFFECTOR)*math.cos(alpha) # distance from base foot frame (robot origin) to motor 4 (or 2, if pivot_foot = 5) along r 
    s = Pz + (L4 + L_ENDEFFECTOR) * math.sin(alpha) - (L_BASE + L1)  # Vertical (z) distance from joint 2 to joint 4. 

    # Intermediate angles and sides
    c = math.sqrt(r_4**2 + s**2) # 3D distance between Joints 2 & 4 
    cos_beta = (L2**2 + c**2 - L3**2) / (2 * L2 *  c) #  = cos(beta)
    cos_phi = (L2**2 + L3**2 - c**2) / (2 * L2 * L3) # = cos(phi) where phi is the angle at Joint 3, between L2 & L3 

    if(cos_beta**2 > 1) or (cos_phi**2 > 1): # prevents imaginary numbers from happening later, aka prevent out of workspace
        raise ValueError("out of bounds bleh :P")
    
    beta = math.atan2(math.sqrt(1 - cos_beta**2), cos_beta) # the angle at joint 2 between L2 & c 
    phi =  math.atan2(math.sqrt(1 - cos_phi**2), cos_phi) # the angle at joint 3, between L2 & L3
    gamma = math.atan2(s, r_4) # at joint 2, the angle between c & the "r axis"
    
    theta3 = round(math.pi - phi, 2) # Theta3 is not dependent on which_foot
    # Depending on which motor (leg) is used, calculate the angles differently
    if pivot_foot == 1:
        #theta 1
        y = math.sqrt(1 - (Px/r)**2) 
        if (Py < 0):
            theta1 = math.atan2(-y, Px/r)
        else:
            theta1 = math.atan2(y, Px/r) 
        
        # Final joint angles
        theta2 = round(math.pi/2 - beta - gamma, 2)
        theta4 = round(theta2 + theta3 - alpha - math.pi/2, 2) 

        # Joint 5 doesn't affect the pose 
        if (fix_EE_orientation): 
            theta5 = 0
        else: 
            if Py > 0: # Y value is positive aka turning left
                theta5 = theta1 + 90
            else: 
                theta5 = theta1 - 90

    elif pivot_foot == 5:
        #theta 5
        y = math.sqrt(1 - (Px/r)**2) 
        if (Py < 0):
            theta5 = math.atan2(-y, Px/r)
        else:
            theta5 = math.atan2(y, Px/r) 
    
        # Final joint angles
        theta4 = - round(math.pi/2 - (beta + gamma), 2)
        theta2 = - round(-theta4 + theta3 - alpha - math.pi/2, 2)

        # Joint 1 doesn't affect the pose 
        if (fix_EE_orientation): 
            theta1 = 0
        else: 
            if Py < 0: # Y value is negative aka turning left
                theta1 = theta5 + 90
            else: 
                theta1 = theta5 - 90

    else:
        raise ValueError('ERROR: please choose either leg 5 or leg 1')

    # Convert radians to degrees
    theta1 = math.degrees(theta1)
    theta2 = math.degrees(theta2)
    theta3 = math.degrees(theta3)
    theta4 = math.degrees(theta4)
    theta5 = math.degrees(theta5)

    # storing all the theta values in a list 
    theta_values = [theta1, theta2, theta3, theta4, theta5] 

    # adjusting the theta values with inchworm motor offsets
    theta_values = apply_offsets(theta_values, inchworm_motor_offsets)

    # check if the theta values are within the bounds
    check_motor_bounds(theta_values, inchworm_motor_bounds)
    
    print ("In IK theta values: ", theta_values)

    
    # return the theta values
    return theta_values
