motor_offsets: 
  theta1: 137.0
  theta2: 103.0
  theta3: 26.0
  theta4: 130.0
  theta5: 150.0

motor_bounds:
  joint1_outer_bound: 
  joint1_inner_bound:
  joint2_outer_bound: 70.0 
  joint2_inner_bound: 245.0 
  joint3_outer_bound: -5.0
  joint3_inner_bound: 175.0 
  joint4_outer_bound: 168.0 
  joint4_inner_bound: -7.0 
  joint5_outer_bound: 
  joint5_inner_bound:
